force-app/main/default/objects/AnonymizationConfiguration__mdt/AnonymizationConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>Anonymization Configuration</label>
    <pluralLabel>Anonymization Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/AnonymizationConfiguration__mdt/fields/SobjectAPIName__c.field-meta.xml
<CustomField>
    <fullName>SobjectAPIName__c</fullName>
    <label>Sobject API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestBaseAnonymizator.cls
@isTest
public class TestBaseAnonymizator {
    
    @isTest
    static void testDeletion() {
        System.Test.loadData(Account.sObjectType, 'TestAccounts');

        final AnonymizationConfiguration__mdt accountConfig = findConfigFor('Account');

        System.assert([SELECT Id FROM Account].size() > 0);

        System.Test.startTest();
            AnonymizationBatch batch = new AnonymizationBatch(new List<AnonymizationConfiguration__mdt> { accountConfig });
            Database.executeBatch(batch);
        System.Test.stopTest();

        System.assert([SELECT Id FROM Account].size() == 0);
    }

    // Static resource has to be updated
    @isTest
    static void testAnonymization() {
        System.Test.loadData(Account.sObjectType, 'TestRecentAccounts');

        final AnonymizationConfiguration__mdt accountConfig = findConfigFor('Account');

        System.assert([SELECT Id FROM Account].size() > 0);

        System.Test.startTest();
            AnonymizationBatch batch = new AnonymizationBatch(new List<AnonymizationConfiguration__mdt> { accountConfig });
            Database.executeBatch(batch);
        System.Test.stopTest();

        System.assert([SELECT Id FROM Account].size() > 0);
    }

    public static AnonymizationConfiguration__mdt findConfigFor(String sobjectAPIName) {
        final List<AnonymizationConfiguration__mdt> configs = AnonymizationConfiguration__mdt.getAll().values();
        final AnonymizationConfiguration__mdt accountConfig;
        for (AnonymizationConfiguration__mdt config: configs) {
            if (config.SobjectAPIName__c == sobjectAPIName) {
                accountConfig = config;

                break;
            }
        }

        return accountConfig;
    }
}